name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # change if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build   # ensure this outputs to your publish_dir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.AUTO_DEPLOY_KEY }}
          publish_dir: ./dist  # replace with your build output folder
